# pull official base image
#FROM python:3.11.5-alpine3.17
FROM arm64v8/python:3.10-alpine3.17

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# install dependencies
#RUN apk add g++ gcc
RUN pip install --upgrade pip
RUN apk add g++ build-base python3-dev
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt
RUN pip install opentelemetry-sdk
RUN pip install opentelemetry-instrumentation-django
RUN pip install requests
RUN pip install opentelemetry-exporter-otlp
RUN pip install opentelemetry-distro
RUN pip install opentelemetry-instrumentation
RUN opentelemetry-bootstrap -a install

# copy entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

# copy project
COPY . /usr/src/app/

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
