receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  logzio/traces:
    account_token: ""
    region: "us"
  # logging:
  #   verbosity: detailed
  #   sampling_initial: 5
  #   sampling_thereafter: 200
  prometheusremotewrite:
    endpoint: https://listener.logz.io:8053
    headers:
      Authorization: Bearer

processors:
  batch:
  tail_sampling:
    policies:
      [
        {
          name: policy-errors,
          type: status_code,
          status_code: { status_codes: [ERROR] },
        },
        { name: policy-slow, type: latency, latency: { threshold_ms: 1000 } },
        {
          name: policy-random-ok,
          type: probabilistic,
          probabilistic: { sampling_percentage: 10 },
        },
      ]

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logzio/traces]
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite]
  telemetry:
    logs:
      level: "info"
